//
//  testfile.swift
//  GulfExchangeApp
//
//  Created by macbook on 31/08/2024.
//  Copyright © 2024 Oges. All rights reserved.
//

/*import Foundation
{
           "id": 40668,
           "x_for_employee_type": false,
           "name": "MyHotels",
           "x_offer_type": "promocode",
           "image_url": "https://golalita.com/go/api/image/40668/image_512/product.template",
           "lst_price": 0.0,
           "default_code": false,
           "x_point": 0.0,
           "x_online_store": true,
           "max_quantity": 0.0,
           "x_offer_type_discount": 0.0,
           "x_offer_type_promo_code": "WALA18",
           "x_merchant_online_store": "https://www.myhotels.sa/hotel",
           "x_buy_link": false,
           "barcode": false,
           "description": false,
           "description_sale": false,
           "x_description_arabic": false,
           "offer_label": false,
           "merchant_id": 25979,
           "categ_id": [
               1,
               "All"
           ],
           "create_date": "2024-02-18 11:59:33",
           "start_date": "2024-02-17 20:00:00",
           "end_date": "2024-03-30 20:00:00",
           "min_quantity": 0.0,
           "discount": 0.0,
           "ribbon": "15% Discout",
           "merchant_name": "MyHotels",
           "merchant_rating": 4,
           "category_id": 1,
           "category_name": "All",
           "disc_ribbon": false,
           "point": 0.0,
           "product_merchant_is_business_hotel": 25979,
           "merchant_logo": "https://golalita.com/go/api/image/25979/image_1920/res.partner"
       },

{
           "id": 43249,
           "x_for_employee_type": false,
           "name": "Standard Twin Room",
           "x_offer_type": "discount",
           "image_url": "https://golalita.com/go/api/image/43249/image_512/product.template",
           "lst_price": 0.0,
           "default_code": false,
           "x_point": 0.0,
           "x_online_store": false,
           "max_quantity": 0.0,
           "x_offer_type_discount": 0.0,
           "x_offer_type_promo_code": false,
           "x_merchant_online_store": "https://treffenhouse.com/?fbclid=IwY2xjawEt8vlleHRuA2FlbQIxMAABHWWHyO25uSdlfE-FdWw1-W0Yzx_3MuM4TQYmyqN0dM97MGFVzGJFTUiJKg_aem_rKkX3v84DVyIo7HGKOB0cg",
           "x_buy_link": false,
           "barcode": false,
           "description": false,
           "description_sale": "",
           "x_description_arabic": false,
           "offer_label": false,
           "merchant_id": 33347,
           "categ_id": [
               1,
               "All"
           ],
           "create_date": "2024-08-17 21:43:55",
           "start_date": "2024-05-25 22:00:00",
           "end_date": "2024-12-30 22:00:00",
           "min_quantity": 0.0,
           "discount": 0.0,
           "ribbon": "15% Discout",
           "merchant_name": "Treffen House",
           "merchant_rating": 4,
           "category_id": 1,
           "category_name": "All",
           "disc_ribbon": false,
           "point": 0.0,
           "product_merchant_is_business_hotel": 33347,
           "merchant_logo": "https://golalita.com/go/api/image/33347/image_1920/res.partner"
       },
{
            "id": 33053,
            "x_for_employee_type": false,
            "name": "Spa Offer",
            "x_offer_type": "b1g1",
            "image_url": "https://golalita.com/go/api/image/33053/image_512/product.template",
            "lst_price": 0.0,
            "default_code": false,
            "x_point": 0.0,
            "x_online_store": false,
            "max_quantity": 0.0,
            "x_offer_type_discount": 0.0,
            "x_offer_type_promo_code": false,
            "x_merchant_online_store": " https://www.theroyalrivierahotel.com.qa/",
            "x_buy_link": false,
            "barcode": false,
            "description": "open the page you will receive the code directly from the merchant",
            "description_sale": "This SPA is inside The Royal Riviera",
            "x_description_arabic": "افتح الصفحة وسوف تحصل على الكود مباشرة من المتجر",
            "offer_label": false,
            "merchant_id": 23233,
            "categ_id": [
                1,
                "All"
            ],
            "create_date": "2023-08-23 08:09:24",
            "start_date": "2023-07-18 20:00:00",
            "end_date": "2023-08-18 20:00:00",
            "min_quantity": 0.0,
            "discount": 0.0,
            "ribbon": "15% Discout",
            "merchant_name": "The Royal Riviera SPA",
            "merchant_rating": 4,
            "category_id": 1,
            "category_name": "All",
            "disc_ribbon": false,
            "point": 0.0,
            "product_merchant_is_business_hotel": 23233,
            "merchant_logo": "https://golalita.com/go/api/image/23233/image_1920/res.partner"
        },
{
            "id": 43250,
            "x_for_employee_type": false,
            "name": "All-Inclusive Summer flyer",
            "x_offer_type": false,
            "image_url": "https://golalita.com/go/api/image/43250/image_512/product.template",
            "lst_price": 999.0,
            "default_code": false,
            "x_point": 0.0,
            "x_online_store": false,
            "max_quantity": 0.0,
            "x_offer_type_discount": 0.0,
            "x_offer_type_promo_code": false,
            "x_merchant_online_store": "https://www.facebook.com/rixosgulfdoha/",
            "x_buy_link": "https://www.facebook.com/rixosgulfdoha/",
            "barcode": false,
            "description": "All-Inclusive Summer flyer",
            "description_sale": "All-Inclusive Summer flyer",
            "x_description_arabic": false,
            "offer_label": false,
            "merchant_id": 22938,
            "categ_id": [
                1,
                "All"
            ],
            "create_date": "2024-08-25 08:01:27",
            "start_date": false,
            "end_date": false,
            "min_quantity": 0.0,
            "discount": 0.0,
            "ribbon": "15% Discout",
            "merchant_name": "RIXOS GULF HOTEL DOHA",
            "merchant_rating": 4,
            "category_id": 1,
            "category_name": "All",
            "disc_ribbon": false,
            "point": 0.0,
            "product_merchant_is_business_hotel": 22938,
            "merchant_logo": "https://golalita.com/go/api/image/22938/image_1920/res.partner"
},
*/
